#!/bin/bash

set -euo pipefail

readonly pr_commit="${1:-core-dev}"

# Autogenerate a branch name based on the commit subject.
readonly branch_name="$(git show --no-patch --format="%f" "$pr_commit")"

# Create the new branch and switch to it.
git branch --no-track "$branch_name" origin/core-dev
git switch "$branch_name"

# Cherry pick the desired commit.
if ! git cherry-pick "$pr_commit"; then
    git cherry-pick --abort
    git switch core-dev
    exit 1
fi

# Create a new remote branch by the same name.
git -c push.default=current push

open "https://gitlab.com/fastr/mono/merge_requests/new?merge_request[source_branch]=$branch_name"

# Go back to core-dev branch.
git switch core-dev
